version: '3.8'

services:
   billbot:
    build:
      context: .
    container_name: billbot
    volumes:
    - ./data:/data
    environment:
    - TOKEN=${TOKEN}
    - PREFIX=.
    - RUNTIME_ENV=${RUNTIME_ENV}
    - WOLFRAM_APPID=${WOLFRAM_APPID}
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - OWNER_ID=${OWNER_ID}
    - SERVER_ID=${SERVER_ID}
    - MONGO_DB_URI=${MONGO_DB_URI}
